### ISSUE TITLE
关于CxAM与CnAM注意力模块的问题

### ISSUE THREAD

**Issue by Bin-ze** [Caojunxu/AC-FPN#9]
我想问一下FPN上的注意力模块在哪里进行了实现，是在FPN.py吗，我在里面似乎没有找关于这些模块的搭建。感谢！

**Comment by VectNull** [comment]
同问，您找到了吗

**Comment by Bin-ze** [comment]
这是好久之前的事情了，当时读了这篇论文，所以想看一下代码，最后我发现他的repo里写到没有关于这两个模块的实现，所以我就没有再继续研究这个问题了

发自我的iPhone

**Comment by VectNull** [comment]
> 这是好久之前的事情了，当时读了这篇论文，所以想看一下代码，最后我发现他的repo里写到没有关于这两个模块的实现，所以我就没有再继续研究这个问题了 发自我的iPhone
> […](#)
> 在 2022年4月10日，21:52，wangsigong ***@***.***> 写道： ﻿ 同问，您找到了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

那您后续有没有找过比较容易实现，比较容易插入到现有模型中的改进的FPN呢

**Comment by Bin-ze** [comment]
关于类fpn的研究太多了，你要是对此感兴趣，可以在谷歌学术或者其他地方进行了解，类似的经典fpn网络如pafpn，pifpn等等，都是不错的选择，有着稳定的性能提升

发自我的iPhone

**Comment by VectNull** [comment]
> 关于类fpn的研究太多了，你要是对此感兴趣，可以在谷歌学术或者其他地方进行了解，类似的经典fpn网络如pafpn，pifpn等等，都是不错的选择，有着稳定的性能提升 发自我的iPhone
> […](#)
> 在 2022年4月10日，23:18，wangsigong ***@***.***> 写道： ﻿ 这是好久之前的事情了，当时读了这篇论文，所以想看一下代码，最后我发现他的repo里写到没有关于这两个模块的实现，所以我就没有再继续研究这个问题了 发自我的iPhone … 在 2022年4月10日，21:52，wangsigong @.***> 写道： ﻿ 同问，您找到了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. 那您后续有没有找过比较容易实现，比较容易插入到现有模型中的改进的FPN呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

好的，谢谢解答

**Comment by yzy12-max** [comment]
> 这是好久之前的事情了，当时读了这篇论文，所以想看一下代码，最后我发现他的repo里写到没有关于这两个模块的实现，所以我就没有再继续研究这个问题了 发自我的iPhone
> […](#)
> 在 2022年4月10日，21:52，wangsigong ***@***.***> 写道： ﻿ 同问，您找到了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

**Comment by yzy12-max** [comment]
> 同问，您找到了吗

代码里没找到，连基础的CEM模块，我发现和论文都有出入，好像没加可变形卷积块

**Comment by VectNull** [comment]
好的好的谢谢，那您知道有什么比较好的FPN的改进，而且易于插入到现有模型中的FPN嘛



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月10日(星期天) 晚上11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Caojunxu/AC-FPN] 关于CxAM与CnAM注意力模块的问题 (#9)





 这是好久之前的事情了，当时读了这篇论文，所以想看一下代码，最后我发现他的repo里写到没有关于这两个模块的实现，所以我就没有再继续研究这个问题了 
 
 发自我的iPhone 
 
 &gt; 在 2022年4月10日，21:52，wangsigong ***@***.***&gt; 写道： 
 &gt;  
 &gt; ﻿ 
 &gt; 同问，您找到了吗 
 &gt;  
 &gt; — 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe. 
 &gt; You are receiving this because you authored the thread.

**Comment by Bin-ze** [comment]
Multi-level feature fusion pyramid network for object detection 
你谷歌学术上可以看下
